---
- name: Copy configuration
  ansible.builtin.template:
    src: server.hcl.j2
    dest: /etc/consul.d/server.hcl
  notify:
    - daemon-reload
    - restart consul.service

- name: Setup folder permissions
  file:
    path: /etc/consul.d
    state: directory
    recurse: yes
    owner: '{{ consul_user }}'
    group: '{{ consul_group }}'

- name: Setup file permissions
  file:
    path: /etc/consul.d/server.hcl
    mode: '640'

- name: Allow firewall rule
  ansible.posix.firewalld:
    port: 8500/tcp
    permanent: yes
    state: enabled
    immediate: yes
