---
- name: Create node_exporter folder
  ansible.builtin.file:
    state: directory
    name: /opt/exporter/node_exporter

- name: Check if node-exporter is already installed
  ansible.builtin.stat:
    path: /usr/local/bin/node_exporter
  register: node_exporter

- name: Download last version of node-exporter
  ansible.builtin.get_url:
    url: 'https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz'
    dest: /tmp/node_exporter.tar.gz
  when: not node_exporter.stat.exists or node_exporter_force_install

- name: Extract latest binary of node-exporter
  ansible.builtin.unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /opt/exporter/node_exporter
    remote_src: yes
    list_files: yes
  register: archive_contents
  when: not node_exporter.stat.exists or node_exporter_force_install

- name: Copy node-exporter binary to /usr/local/bin
  ansible.builtin.copy:
    src: '/opt/exporter/node_exporter/{{ archive_contents.files[0] }}node_exporter'
    dest: /usr/local/bin/node_exporter
    mode: 0700
    remote_src: yes
  notify: restart node_exporter.service
  when: not node_exporter.stat.exists or node_exporter_force_install

- name: Create config file
  ansible.builtin.template:
    src: node_exporter.j2
    dest: /etc/sysconfig/node_exporter

- name: Create systemd service file
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
  notify:
    - daemon-reload
    - enable node_exporter.service
    - restart node_exporter.service

- name: Allow firewall rule
  ansible.posix.firewalld:
    port: 9100/tcp
    permanent: yes
    state: enabled
    immediate: yes
