---
- name: daemon-reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted

- name: enable dotnet.service
  ansible.builtin.systemd:
    name: 'dotnet-{{ item.name }}'
    enabled: yes
  with_items: '{{ sites }}'

- name: restart dotnet.service
  ansible.builtin.systemd:
    name: 'dotnet-{{ item.name }}'
    state: restarted
  with_items: '{{ sites }}'
