---
- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted

- name: start nginx
  ansible.builtin.systemd:
    name: nginx
    state: started

- name: enable nginx
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
