- name: Install qemu-guest-agent
  hosts: "new"
  tasks:
    - name: install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present
        update_cache: true
      become: true

# ansible-playbook ./playbooks/qemu-guest-install.yml -i ./hosts