---
- name: daemon-reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: restart node_exporter.service
  ansible.builtin.systemd:
    name: node_exporter.service
    state: restarted

- name: enable node_exporter.service
  ansible.builtin.systemd:
    name: node_exporter.service
    enabled: yes
