---
- name: Configure Monitoring
  hosts: monitoring
  become: yes
  roles:
    - rhel-subscription
    - prometheus
    - alertmanager
    - grafana
    - vmware_exporter

- name: Configure Consul Servers
  hosts: consul
  become: yes
  roles:
    - consul-all
    - consul-server
