---
- name: Configure Monitoring
  hosts: monitoring
  become: yes
  roles:
    - rhel-subscription
    - prometheus
    - alertmanager
    - grafana
    - vmware_exporter
    - awair_exporter
# - name: Configure Consul Servers
#   hosts: consul
#   become: yes
#   roles:
#     - consul-all
#     - consul-server

# - name: Configure Test Server
#   hosts: rhel
#   become: yes
#   roles:
#     - rhel-subscription
#     - nginx
#     - dotnet-app

# - name: Configure Web Server 2 Server
#   hosts: dotnet
#   become: yes
#   roles:
#     - rhel-subscription
#     - dotnet-app

# - name: Configure RHEL9 Server
#   hosts: rhel9
#   become: yes
#   roles:
#     - rhel-subscription
#     - awair_exporter
