---
- name: Configure RHEL Image
  hosts: default
  become: true
  vars:
  roles:
    - users
    - node_exporter
  # pre_tasks:
  #   - name: Update Packages
  #     yum:
  #       name: '*'
  #       state: latest
  #       update_cache: yes

  #   - name: Include Utils
  #     include_tasks: ./playbooks/utils.yml
  tasks:
    - name: 'Update {{ main_user }} password'
      user:
        name: '{{ main_user }}'
        password: "{{ main_password | password_hash('sha512') }}"
        update_password: always
