---
- hosts: linux
  tasks:
    - name: Install updates
      dnf:
        name: '*'
        state: latest
        update_cache: yes
        update_only: yes
      become: true
# ansible-playbook -i ./hosts -k ./updates.yml
